twig:
    default_path: '%kernel.project_dir%/templates'
    #form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # liste_deces_tabs: '%env(LISTE_DECES_TABS)%'

when@test:
    twig:
        strict_variables: true
