version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.11'
    container_name: hosp_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

  dbadmin:
    image: 'phpmyadmin:latest'
    container_name: hosp_dbadmin
    environment:
      PMA_HOST: database
    depends_on:
      - database
    ports:
      - 8100:80

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    container_name: hosp_mailer
    ports: [1025, 1080]
###< symfony/mailer ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
